server:
  port: 81
spring:
  redis:
    host: 192.168.147.100
    port: 6379
    password: 111111
    database: 0
  cache:
    redis:
      time-to-live: 180000 #设置缓存数据过期时间
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.147.100:3306/sanyu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.147.101:3306/sanyu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
    masterslave:
      #读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      #最终的数据源名称
      name: datasource
      #主库数据源
      master-data-source-name: master
      #从库数据源，列表，逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启sql显示，默认false
  main:
    allow-bean-definition-overriding: true #允许bean定义覆盖配置项


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
